### ISSUE TITLE
Make `clan` optional

### ISSUE THREAD

**Issue by DiniFarb** [DiniFarb/codewars_readme_stats#22]
I came across some profiles and saw that some do not have set a clan in codewars. For a cleaner card it should be possible to disable the `clan` text. Might add parameter `displayClan=false`. 

Or perhaps it would be better to add some sort of array parameter like: `ignore=clan:honor` for letting people ignore what ever they don't wont on the card.

**Comment by VitorEstevam** [comment]
i've created a PR to do this. Please, take a look

**Comment by DiniFarb** [comment]
Thanks also for this PR 😊 I have merged it, got a little conflict. I should have merged this befor #27 😄

**Comment by VitorEstevam** [comment]
Nice! I think this issue can be closed, but the option is not available here
