### ISSUE TITLE
Use templates instead of manual parsing

### ISSUE THREAD

**Issue by VitorEstevam** [DiniFarb/codewars_readme_stats#26]
I think we can use templates do render the SVG instead of doing manual parsing of the components. With this the code would be more maintenable and a few features like dinamic height could implemented in a easier way

**Comment by VitorEstevam** [comment]
I now this is a big refactor, but i think this can be done by small PRslike: One for theming, one for fields, etc

**Comment by VitorEstevam** [comment]
one reference: https://groups.google.com/g/golang-nuts/c/KmM2brW4UEA/m/UBepULN9dwsJ

**Comment by VitorEstevam** [comment]
The PR applying templates to the theme were merged but suggest keeping this issue open for more refactors like this :)

**Comment by DiniFarb** [comment]
Yes there is still work to do :)
