### ISSUE TITLE
Inspierd to inspired on the bottom  in Additional sections 

### ISSUE THREAD

**Issue by HyunCafe** [DiniFarb/codewars_readme_stats#29]
Inspierd to inspired on the bottom  in Additional sections

**Comment by DiniFarb** [comment]
What do you mean, did you open that issue because you want to come up with some ideas for a additional bottom section ?

**Comment by HyunCafe** [comment]
on the bottom of your readme inspierd is mis spelled- should be Inspired 

Additional
Inspierd by https://github.com/anuraghazra/github-readme-stats

Icons are from https://simpleicons.org/

If you have any questions don't hesitate open a issue!

**Comment by DiniFarb** [comment]
Oh, yes thx 😊
