### ISSUE TITLE
Animation disable option

### ISSUE THREAD

**Issue by Burndowntheworld** [DiniFarb/codewars_readme_stats#43]
Is it possible to add a query to disable animations? `&animations=true` at the end of the url for other to be a still image.

**Comment by DiniFarb** [comment]
Well this is not yet possible but could be added. Were you thinking of opening a PR ?  :)

**Comment by Burndowntheworld** [comment]
Im gonna be honest.im not sure how to do that or what that is.

**Comment by DiniFarb** [comment]
I was just asking if you yourself want to implement that feature and then opening a pull request to this repository. :) But don't worry, I can implemented it. It will take a while though, cos I am limited in time at the moment.

**Comment by DiniFarb** [comment]
closed with https://github.com/DiniFarb/codewars_readme_stats/commit/86d49755957da3c5a623d43e8acaf37327152d79
