### ISSUE TITLE
Not all icons are displayed correctly

### ISSUE THREAD

**Issue by DiniFarb** [DiniFarb/codewars_readme_stats#7]
For matching the right icon of `simple-icons` lib the name of the language from codewars is used:
[in this function](https://github.com/andreasvogt89/codewars_readme_stats/blob/b5dd617e9b0eeb9436bcf5c4e4c18e63592c2ac1/src/routes/codewars.js#L81)

If the name does not match any icon in the `simple-icons` it tries to match it with a mapping in the `specialIcons` object.

```js
const specialIcons = {
  shell: {
    name:"windowsterminal",
    display_name:"Windows Terminal"
  }
}
```
This object needs to be extended or even better a other smarter logic has to be implemented.

**Comment by harshita2216** [comment]
May I please work on this?

**Comment by andreasvogt89** [comment]
Very happy to take your help 👍🏽

**Comment by andreasvogt89** [comment]
After the golang migration, this is still a problem but the way the icons are loeaded has slighty changed. New they are stored [here](https://github.com/andreasvogt89/codewars_readme_stats/tree/master/codewars/templates/icons) in this repo as svg's. The missing icons should be added there, as soons as I can manage I'll try to find n add them.

**Comment by DiniFarb** [comment]
I have sterted with adding a SQL icon. => [4ce4497](https://github.com/DiniFarb/codewars_readme_stats/commit/4ce449710fd504950f8a6958d19002c9894f4ba7)

Tracking list:
- [ ] fsharp
- [ ] cpp   
- [x] sql   
- [ ] objc  
- [ ] groovy
- [ ] vb
- [ ] forth
- [ ] factor
- [ ] prolog
- [ ] cobol
- [ ] coq
- [ ] cfml
- [ ] commonlisp
- [ ] raku
- [ ] pascal
- [ ] bf
- [ ] nasm
- [ ] idris
- [ ] agda
- [ ] lean
